### ISSUE TITLE
Resulting HTML has too much whitespaces

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#10]
Just have checked resulting HTML

Same site generated using

original reflow plugin: https://om.alteametasoft.com/openmeetings/docs/
1.2.3 version: https://om.alteametasoft.com:8443/next/docs/

1. Lots of whitespaces in the beginning and between Menu blocks
2. Top of document

Hot sure how critical is this, but would be nice to fix

**Comment by devacfr** [comment]
I waited have a good velocity editor

**Comment by devacfr** [comment]
Work done and available in version 1.3.0-DEVACFR

Your Welcome.

**Comment by solomax** [comment]
Thanks a lot!
Just have checked, works as expected!
is it already available in central?

**Comment by devacfr** [comment]
This is available on maven central:
```
<dependency>
  <groupId>io.github.devacfr.maven.skins</groupId>
  <artifactId>reflow-velocity-tools</artifactId>
  <version>1.3.3</version>
</dependency>
```

**Comment by solomax** [comment]
I can't see it 
here: https://repo1.maven.org/maven2/io/github/devacfr
and here: http://mvnrepository.com/search?q=reflow

:((((

**Comment by devacfr** [comment]
For me, it is first time a release in  maven central. I forgot to run release action. Now it is available.

**Comment by solomax** [comment]
Works as expected
Thanks for publishing :)
