### ISSUE TITLE
TOC issues for headers with same labels

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#14]
The following configurations will fail:

Carousel is enabled:
```
<section name="Test"></section>
<hr/>
<section name="Features">
    <subsection name="Test"></subsection>
</section>
```
In this case second `Test` will be listed in TOC, but will not be hightlighted, and will not move to correct part of the page

Carousel is disabled
```
<section name="Test1">
    <h3 name="Prerequicite"></h3>
    <h3 name="Steps"></h3>
</section>
<section name="Test2">
    <h3 name="Prerequicite"></h3>
    <h3 name="Steps"></h3>
</section>
```
Will display correct TOC, but all links from `Test2->h3*` will point to `Test1->h3*`

**Comment by devacfr** [comment]
See commit https://github.com/devacfr/reflow-maven-skin/commit/2a52356119170bce9a8e5e19219d88bf251a520b for check.

Best regards,

**Comment by solomax** [comment]
Seems to work as expected!
Thanks for the quick fix!

**Comment by devacfr** [comment]
do you want publish a snapshot on https://oss.sonatype.org/content/repositories/snapshots/ ?

**Comment by solomax** [comment]
I have tested using local build
Will wait for release :)

**Comment by devacfr** [comment]
I can produce for this day ?!

**Comment by solomax** [comment]
I have renamed TOC items for now.
So no rush :) Let the release has #15 implemented
Without floated sidebar no-one will notice this issue :)

**Comment by devacfr** [comment]
👍
