### ISSUE TITLE
Add affix on toc side bar

### ISSUE THREAD

**Issue by devacfr** [devacfr/reflow-maven-skin#15]

**Comment by solomax** [comment]
I have implemented it as follows: https://github.com/apache/openmeetings/blob/master/openmeetings-server/src/site/resources/js/site.js#L26

**Comment by devacfr** [comment]
Thank you, I prefer affix (manage top and bottom). You can see sample on branch 15-add-affix-on-toc-side-bar. But no worry, this feature will be optional to keep compatibility.

**Comment by solomax** [comment]
Wasn't aware it works from both sides
Will double-check :)

**Comment by devacfr** [comment]
the work is in progress.

**Comment by devacfr** [comment]
I publish a snapshot version of site.

**Comment by solomax** [comment]
Hello @devacfr,

just have tested with local build of branch "feature/15-add-affix-on-toc-side-bar"
with `<toc type="fixed">` 

TOC was NOT fixed, it was scrolled out
Header still overlaps on browser resize ...

Should I test another branch?

**Comment by devacfr** [comment]
Hil @solomax, I are you sure?

- Normally the overlapping is fixed between body and top fixed nav bar.
- `fixed` means, when you scroll up and down the page, the side bar is always visible and locked in its position
- `static` means, the side bar scroll with body.

See http://devacfr.github.io/reflow-maven-skin/skin/toc-sidebar.html


Just missing button to display 'fixed' side bar for mobile device.

**Comment by solomax** [comment]
Just have double-checked:

1. checkout to `feature/15-add-affix-on-toc-side-bar`(check changes using `git diff`)
2. removed my home-made code for sidebar
3. re-build side for my app
4. open page with and without `carousel`

Results:

1. no errors in dev console
2. TOC has attribute `data-spy="affix"`, and class `affix-top`
3. On scroll class is being changed to `affix`
BUT TOC is being scrolled only 20px or so ....

http://devacfr.github.io/reflow-maven-skin/skin/toc-sidebar.html works for me as expected

will try to further investigate this evening

**Comment by solomax** [comment]
My bad, the issue was with my custom css
TOC works as expected
sorry for the noise :((

**Comment by solomax** [comment]
The issue with overlapping is still here :(
It is being caused by the fact topbar is changing it's height
Maybe there are some options to fix topbar height?

**Comment by devacfr** [comment]
Could you deploy a version or maybe I can clone OpenMeetings to test ?

**Comment by devacfr** [comment]
I had the same problem on device size, where the nav bar reduced to 20px on scrolling. I resolve the problem to change padding in .subfooter  to margin.

**Comment by solomax** [comment]
@devacfr sorry was out on the way home :)

you can see this overlapping here: https://om.alteametasoft.com:8443/next/docs/
This site was build by 1.3.3, but the effect is the same

`navbar  navbar-default navbar-fixed-top`
is overlapping with `container`

I'll update this location with site created with most recent version in couple of minutes

**Comment by solomax** [comment]
https://om.alteametasoft.com:8443/next/docs/ is update

**Comment by devacfr** [comment]
@solomax  should be happy. :)

**Comment by solomax** [comment]
Works as expected!
Thanks a lot!
Would like to additionally test final version and will wait for release :)

**Comment by devacfr** [comment]
I can wait, I'm working on another project...

**Comment by solomax** [comment]
Can you please merge #14 and #15 to develop
I'll test in a minute :)

**Comment by devacfr** [comment]
done.

**Comment by solomax** [comment]
Everything works as expected!
Thanks a lot!

**Comment by devacfr** [comment]
Can I release?

**Comment by solomax** [comment]
Sure, please :)

**Comment by devacfr** [comment]
ok ready about 1 hour
