### ISSUE TITLE
Top navbar overlaps with header

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#16]
Top navbar overlaps with header

Steps:

1. Go to http://devacfr.github.io/reflow-maven-skin/skin/components.html
2. Resize browser to have minimum allowed width
Result: overlap

Somehow Original plugin (1.1.1) doesn't overlap: http://openmeetings.apache.org/

**Comment by devacfr** [comment]
The original doesn't work on Bootstrap 3x!

I attached this bug to issue #14.
