### ISSUE TITLE
Second level menu on mobile devices

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#20]
It seems second level menu items are being hardly accessible on mobile devices

Steps:
1) go to https://builds.apache.org/view/M-R/view/OpenMeetings/job/OpenMeetings%204.0.x/site/openmeetings-server/index.html on mobile device (I have used android phone)
2) in top menu try to go to Configuration->User Interface->Hot keys
Result: after "touch" "User Interface" menu closes
Expected result: All levels should be accessible

**Comment by devacfr** [comment]
Thank you, I can't work on it for the moment. I'm going to do at middle of January.

**Comment by solomax** [comment]
Will also try to investigate :)
Thanks a lot and Happy NY :)

**Comment by devacfr** [comment]
Hi @solomax,
 Ok ,The problem is that the menu item of submenu is link on a page. the solutions is prevent the browser from opening a URL but allows that if tapped once again in succession. You can find modification on branch 1.3.6

**Comment by solomax** [comment]
Works as expected!
Thanks a lot for the quick fix!
