### ISSUE TITLE
release 1.3.7 seems to be not valid

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#22]
Hello @devacfr,

It seems not all artifacts were pushed to Maven
There is no http://mvnrepository.com/artifact/io.github.devacfr.maven.skins/reflow-parent of version 1.3.7 :(

Could you please re-deploy it?

**Comment by solomax** [comment]
@devacfr ping :)

**Comment by devacfr** [comment]
hello, sorry I'm coming back. I resolved the problem. the new version is 1.3.8 (can not redeploy in maven central)
