### ISSUE TITLE
TOC block overlapping carousel element

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#23]
Recently we got this https://issues.apache.org/jira/browse/OPENMEETINGS-1876 bug report (against reflow 1.3.6)
I have updated to 1.3.8 but this is still an issue :(

Can be checked here: 
https://builds.apache.org/view/M-R/view/OpenMeetings/job/OpenMeetings%204.0.x/site/openmeetings-server/index.html

Works as expected in Chrome latest, overlapping in FF

**Comment by devacfr** [comment]
There two error to fix:
- the breacrumb has z-index (1020) greater than to toc-sidebar (1000)
- the top-offset use default value "70px".
- the calculation of bottom offset is wrong

I will verify whether the top-offset and bottom offset work correctly

**Comment by solomax** [comment]
Thanks a lot!
Will try it right now

**Comment by solomax** [comment]
The issue seems to still reproducible in FF :(((
https://builds.apache.org/view/M-R/view/OpenMeetings/job/OpenMeetings%204.0.x/site/openmeetings-server/index.html

**Comment by solomax** [comment]
My bad :(
I'm using static JS/CSS files, will re-check and report back

**Comment by solomax** [comment]
Seems to be fixed
Thanks a million!

**Comment by solomax** [comment]
It seems I was too fast :(
Re-checked one more time https://builds.apache.org/view/M-R/view/OpenMeetings/job/OpenMeetings%204.0.x/site/openmeetings-server/index.html

And the issue seems to be reproducible :(

**Comment by devacfr** [comment]
I need maybe wait the rendering of carousel to calculate the offset top of sidebar. How do, I don't know but I will find...

**Comment by solomax** [comment]
Here is some code, not sure if it will help:
https://stackoverflow.com/questions/31630393/bootstrap-carousel-show-after-everything-is-loaded

**Comment by devacfr** [comment]
I published a snapshost version.
Now, $('.carousel').carousel() is execute on document ready and the calculation of offset is execute on DOM finished loading.
I simulate latency with "Regular 3G" and disable the cache with FF 60.0.2, that works... I don't understand this problem.
The only solution for me, you should fix the size of carousel if the last update doesn't work... \:)/

**Comment by solomax** [comment]
I have added custom style with hardcoded height
Hope it will fix the issue

Thanks for your efforts!
Will wait for the release :)

**Comment by devacfr** [comment]
Hi @solomax,
Thx and sorry.
The next version 2, toc sidebar will be display on the right outside .row containing body content.

**Comment by solomax** [comment]
@devacfr could you please release 1.3.9? I need to remove snapshot dependency :)
Thanks in advance

**Comment by devacfr** [comment]
Hi @solomax, I published release 1.3.9.

**Comment by devacfr** [comment]
Hi @solomax , 
I discovered a error with new version of jquery. I published a new version 1.3.10

**Comment by solomax** [comment]
Thanks a million!
