### ISSUE TITLE
Update to use customized Bootstrap theme 3.x

### ISSUE THREAD

**Issue by devacfr** [devacfr/reflow-maven-skin#29]
Currently, the documentation references the customization of boostrap 2x
Objective is allow to include customized bootstrap theme 3x (see https://getbootstrap.com/docs/3.3/customize/).

See [Reflow Themes](https://devacfr.github.io/reflow-maven-skin/skin/themes/)

**Comment by solomax** [comment]
Any chance to be able to use `offline` theme?

**Comment by devacfr** [comment]
@solomax which theme.
I'm working on [#28](https://github.com/devacfr/reflow-maven-skin/issues/28) allowing to add web dependencies (boostrap,jquery...) and also bootswatch theme. See latest commit. 
I created a module "reflow-default-webdeps" and after You are just need set in site.xml <localResources>true</localResources> and add following in pom.xml

```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>unpack</id>
            <phase>pre-site</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>io.github.devacfr.maven.skins</groupId>
                  <artifactId>reflow-default-webdeps</artifactId>
                  <version>${project.version}</version>
                  <type>jar</type>
                  <overWrite>false</overWrite>
                  <!-- exclude all highlight styles except the theme in highlightJsTheme property -->
                  <includes>**/css/**/*.css,**/fonts/*,**/js/*.js,**/js/languages/*,**/js/styles/${highlightJsTheme}.min.css</includes>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${project.build.directory}/site</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
You can play with includes and excludes element to fine tune.

**Comment by solomax** [comment]
Hello @devacfr,

just have tried 1.4.3-SNAPSHOT (local build)
And it copies resources! Thanks for that

The only issues I see: following css classes are missing: `alert-primary` `card-text` and maybe some more

**Comment by devacfr** [comment]
hi @solomax,
I'm looking for why there not all bootstrap classes, I'm going resolve this problem (maybe).

**Comment by devacfr** [comment]
Hi @solomax,
yes, in cerulean theme, alert-primary is missing, card is component of bootstrap 4. I would finalize with bootstrap 3 before begin to work on bootstrap 4.
After, I can create sub-modules specific to bootstrap 4, give me feedback!!

**Comment by solomax** [comment]
@devacfr my bad, I should check this :(
Let me me when it will be time to test :)

**Comment by devacfr** [comment]
@solomax, I don't know if it works correctly with bootstrap 4...

**Comment by solomax** [comment]
OK, I'll re-test with bootstap3 and will report the results :)

**Comment by devacfr** [comment]
@solomax that doesn't work with bootstrap 4

**Comment by solomax** [comment]
@devacfr are you planning to release 1.5.0?

**Comment by devacfr** [comment]
@solomax, I planned to release a beta version.  Are you agree ?
I planned this week also release a beta version 2.0.0-beta supporting bootstrap 4x and documentary support (#19).

**Comment by solomax** [comment]
Wow :)
both betas are OK :)
I'll try to test both :)

**Comment by solomax** [comment]
@devacfr 
this is actually why I initially would like to wait for bootstrap4 support
To change everything to 4 :)
I can test develop locally, would it help?

**Comment by devacfr** [comment]
@solomax,
yes, thank you in advance. All remarks are welcome. for comment write in issue #19 please.
