### ISSUE TITLE
Wrong mailing list links are generated

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#40]
Here is the example (generated with 2.0.0-beta2) https://builds.apache.org/view/M-R/view/OpenMeetings/job/openmeetings/site/openmeetings-server/mailing-lists.html

There is no `mailto:` prefix, so links are useless :(

**Comment by devacfr** [comment]
Hello @solomax , 
I hope all is fine, I search to find the problem (nothing).
But, I discover how apache declares mailing list in pom.

https://github.com/apache/maven-parent/blob/master/pom.xml

**Comment by solomax** [comment]
got it
Will fix our build
sorry for the noise

**Comment by devacfr** [comment]
No problem, 
sla 24h 24/24 7/7.

Actually, you are same problem with contributor email.

**Comment by solomax** [comment]
Hmmm
the issue with mailing lists was fixed by adding `mailto:` prefix
The issue with contributor's email wasn't fixed :(
email addresses are displayed as `mailto:real_mail` instead of `real_mail` with `mailto:` in href :(

**Comment by solomax** [comment]
Thanks a million @devacfr for the investigation
I'll contact Maven team regarding this
