### ISSUE TITLE
Source highlighting seems to be broken

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#41]
Hello @devacfr,

I'm using latest 2.0.0beta2 and just noticed source highlighting seems to be broken
I'm using xdoc format and blocks like this `<source><![CDATA[]]></source>` 

This result can be checked here: https://builds.apache.org/view/M-R/view/OpenMeetings/job/OpenMeetings%204.0.x/site/openmeetings-server/RTMPSAndHTTPS.html

Same page generated with 1.4.2 available here: https://om.alteametasoft.com/openmeetings/docs/RTMPSAndHTTPS.html

Shall I add custom styles, or maybe something wrong with generation?

**Comment by solomax** [comment]
This issue is fixed after adding 
```
	<highlightJs>true</highlightJs>
	<highlightJsTheme>github</highlightJsTheme>
```
and unpacking correspondent stylesheet
So I guess only users not using `highlightJs` are affected

**Comment by devacfr** [comment]
Hello @solomax,
I hope you have a good Christmas Eve.
Can I close this issue?

**Comment by solomax** [comment]
Sure, if `<source>` shouldn't work without highlightJs :)

Merry Christmas :)
In Russia main hioliday is NY :) and Christmas is being celebrated Jan 7 :)))
