### ISSUE TITLE
Bad published date is generated if latest maven-site-plugin is used

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#81]
Hello @devacfr,

recently I've changed `maven-site-plugin -> 4.0.0-M1`
This produces `Last Published` date as `$dateFormat.applyPattern( $format ) $i18n.getString( "site-renderer", $locale, "template.lastpublished" ): $dateValue`

(can be checked for ex. here: https://nightlies.apache.org/openmeetings/)

`maven-site-plugin` `3.11.0` and `3.12.0` works as expected

steps to reproduce:

1. clone https://github.com/apache/openmeetings/
2. `cd openmeetings-server`
3. `mvn clean site:site`
4. check target/site/index.html for ex.

**Comment by solomax** [comment]
Might be Doxia issue :(

I can see following placeholder in generated files:

```
Generated by Apache Maven Doxia  at $dateFormat.format( $currentDate )  Rendered using Reflow Maven Skin 2.3.0 (http://devacfr.github.io/reflow-maven-skin)

        <p class="copyright">Copyright &copy;2012-${currentYear}
                 <a href="https://apache.org">Apache Software Foundation</a>
```

**Comment by solomax** [comment]
ping? :))))

**Comment by devacfr** [comment]
HI @solomax, sorry I have health problems. I watch it next week.

**Comment by solomax** [comment]
no rush @devacfr :)
Please take care of yourself :)

**Comment by solomax** [comment]
things are even worse with latest maven-site-plugin `4.0.0-M2` :((((

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:4.0.0-M2:site (generate-site) on project openmeetings-parent: Execution generate-site of goal org.apache.maven.plugins:maven-site-plugin:4.0.0-M2:site failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-site-plugin:4.0.0-M2:site: java.lang.NoSuchMethodError: 'void org.apache.velocity.app.VelocityEngine.setProperties(java.util.Properties)'
[ERROR] -----------------------------------------------------

```

**Comment by solomax** [comment]
Hello @devacfr,
how are you? :)

**Comment by devacfr** [comment]
Hello, I come back. I will try...

**Comment by devacfr** [comment]
After investigation. I need to bump version of Velocity and upgrade the reflow according to it.
This can take a while to verify and test this change.
I going to give feedback and maybe publish a snapshot version if you want.

**Comment by devacfr** [comment]
### Task

- [ ] Need upgrade velocity-tools to 3.1 with new name velocity-tools-generic
- [ ] Upgrade doxia-sitetool to 1.11.1

NB: Some reports may not work yet (clover,rat,...)

**Comment by solomax** [comment]
welcome back @devacfr :)
hope you are better :)))

sure, please share SNAPSHOT as soon you will be ready
will be happy to test :)

**Comment by devacfr** [comment]
@solomax the snapshot 2.3.1-SNAPSHOT version is available in repo https://oss.sonatype.org/content/repositories/snapshots

**Comment by solomax** [comment]
@devacfr just have tested with both `maven-site-plugin:4.0.0-M3` and everything seems to works as expected
no crash and the published date is correct!

Thanks for the fix!

**Comment by solomax** [comment]
@devacfr any ETA for the release? :)

**Comment by devacfr** [comment]
@solomax , I'm overbooked. I hope release this version next week. I'll let you know.

**Comment by solomax** [comment]
@devacfr no rush :)
Thanks a lot for maintaining this plugin :))

**Comment by solomax** [comment]
Hello @devacfr any news on the release date? :))

**Comment by devacfr** [comment]
@solomax, i will do it today

**Comment by devacfr** [comment]
@solomax the release 2.3.1 is available.

**Comment by solomax** [comment]
@devacfr just have updated to the latest version and everything works as expected!
Thanks a lot!

**Comment by jdimeo** [comment]
Thank you for this! this allows me to use the latest Doxia dependencies because I found a rendering performance bug, so I appreciate the work here so we can still use the skin
