### ISSUE TITLE
Specify highlightJS language

### ISSUE THREAD

**Issue by jdimeo** [devacfr/reflow-maven-skin#82]
Thank you for maintaining this fantastic skin.

I am documenting YAML files in my site, and highlightJS "auto" language is always getting it wrong- sometimes it thinks it's SQL, sometimes .properties, etc.

I've generated my markdown with
```
```language-yaml
```

but it doesn't seem to have an effect. Is there a way to enable highlightJS but disable auto detection and use the hint from Markdown?

**Comment by devacfr** [comment]
Hello @jdimeo, Thanks.
Are you test directly the rendering of your yaml with latest version of highlightJS ?
Do you use reflow with local resources (<localResources>true|false</localResources>) ? 
Could you give me link of your project (if possible) ?

**Comment by jdimeo** [comment]
No, I'm just using:
```
<highlightJs>true</highlightJs>
```
and using version **2.3.0** of this skin which looks like it uses **9.15.7** of highlightJS. I'm not using local resources. Unfortunately, I can't share the site because it is internal, but I'm just referencing this part of the documentation:
> It detects the language automatically
https://devacfr.github.io/reflow-maven-skin/doc/reflow-documentation.html#doc-configuration_toc_code-highlight

**Comment by devacfr** [comment]
@jdimeo , could you test your page containing yaml and change manually highlightJS reference using latest version or add &lt;reflowSkin&gt;... &lt;highlightJsVersion&gt;11.6.0&lt;/highlightJsVersion&gt;... &lt;/reflowSkin&gt;?
There are more possibilities: 
- wrong version of highlightJS
- reflow generate wrong html
- and finally you will have to use another highlight renderer.

**Comment by jdimeo** [comment]
Thank you for your fast responses and help!

Yes! Upgrading to **11.6.0** has fixed many issues on most pages. I didn't realize it was as easy as `<highlightJsVersion>`. This is definitely good enough for now. I just thought there might be a way for the language hint to be sent to highlightJS more "directly" (since Markdown supports it) instead of hoping to "get lucky" that the auto-detection of language works.

**Comment by devacfr** [comment]
@jdimeo, the language hint is not recognize by markdown doxia plugin I believe. You can create a issue on my project for investigation.
