### ISSUE TITLE
Reproducible build

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#88]
Hello @devacfr,

I'm trying to create reproducible build
As described here: https://maven.apache.org/guides/mini/guide-reproducible-builds.html

Unfortunately the site generated by "Reflow skin" has following header:
```
<!--
 Generated by Apache Maven Doxia  at 02/07/23  Rendered using Reflow Maven Skin 2.3.1 (http://devacfr.github.io/reflow-maven-skin)
-->
```

It is impossible to override this date using `project.build.outputTimestamp` :(

I also tried to set date as described here: https://devacfr.github.io/reflow-maven-skin/doc/reflow-documentation.html#doc-configuration_toc_date-and-version
But these instructions seems to be outdated :(

`<publishDate position="none"/>` seems to be not an option :(

Would appreciate any advice :))

**Comment by solomax** [comment]
@devacfr Shall I try to reproduce this issue using default/fluido skin? :)

**Comment by devacfr** [comment]
Hello @solomax, I will investigate, I will give feedback.

**Comment by solomax** [comment]
@devacfr Thanks a lot for a quick response :)

**Comment by devacfr** [comment]
@solomax I will create snapshot version 2.3.3-snapshot to include reproduce build associated to publishDate.format and publishDate.position. I inform you when ready.

**Comment by solomax** [comment]
@devacfr Thanks a lot! can't wait to test it :)))

**Comment by devacfr** [comment]
@solomax  the version 2.3.3-SNAPSHOT is available on https://oss.sonatype.org/content/repositories/snapshots/

**Comment by solomax** [comment]
@devacfr superb! both comment and "last Published" header honors `-Dproject.build.outputTimestamp='2023-02-07T04:44:11Z'`
Thanks a lot!

**Comment by devacfr** [comment]
@solomax  can I release ?

**Comment by solomax** [comment]
Yes, please :)
Thanks a lot for the quick and proper fix :)))

**Comment by devacfr** [comment]
@solomax the release 2.3.3 is available.
