### ISSUE TITLE
NPE with maven-site-plugin:4.0.0-M9:site

### ISSUE THREAD

**Issue by solomax** [devacfr/reflow-maven-skin#89]
Hello,

Recently have updated to maven-site-plugin:4.0.0-M9 and got following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:4.0.0-M9:site (generate-site) on project openmeetings-server: Velocity error while merging site template.: Invocation of method 'text' in  class org.devacfr.maven.skins.reflow.HtmlTool threw exception java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null at META-INF/maven/page-default.vm[line 62, column 42] -> [Help 1]
```

using `<reflow-maven-skin.version>2.3.3</reflow-maven-skin.version>`

To reproduce the issue you can run 

`mvn clean site`

repo: https://github.com/apache/openmeetings
branch: `maven-site-M9`

I'll be happy to test new version :)

**Comment by devacfr** [comment]
Hello @solomax, 
I published a new snapshot version 2.3.4-SNAPSHOT

**Comment by solomax** [comment]
Thanks @devacfr !

This version works as expected with `maven-site-plugin:4.0.0-M9`, but fails with `maven-site-plugin:4.0.0-M5`

Is it by design? :)

**Comment by devacfr** [comment]
Hi @solomax,

maven-site-plugin:4.0.0-M9 uses doxia-site-model that replaces doxia-decoration-model. If the backward compatibility is required, I can try to do it

**Comment by solomax** [comment]
@devacfr I guess backward compatibility is not required (at least not by our project :))), but it worth to be mentioned somewhere :)

**Comment by solomax** [comment]
Thanks for the fast fix :)

**Comment by devacfr** [comment]
@solomax ,
I need complete documentation on compatibility with maven-site-plugin and release it.

**Comment by devacfr** [comment]
@solomax , The release 2.3.4 is available

**Comment by solomax** [comment]
Thanks a million for the release! :))
